---

- name: "Insert aliases in aliases file"
  blockinfile:
    dest: "{{ alias_path }}"
    insertafter: "^ Custom alias file$"
    marker: "# ANSIBLE - ALIAS LIST {mark}"
    block: "{{ alias_list }}"
