---

- name: "Inserting plugins in {{ zshrc_path }}"
  blockinfile:
    dest: "{{ zshrc_path }}"
    insertafter: "^plugins=.*"
    marker: "# ANSIBLE - OH MY ZSH PLUGIN LIST {mark}"
    block: "{{ plugins_list }}"

- name: "Inserting custom paths in {{ zshrc_path }}"
  blockinfile:
    dest: "{{ zshrc_path }}"
    insertafter: "^# Custom paths$"
    marker: "# ANSIBLE - ZSH CUSTOM PATHS {mark}"
    block: "{{ alias_list }}"
